title: "Software Tools in JavaScript"
copyrightYear: 2020
repo: https://github.com/gvwilson/e/
rootDir: "."
siteDir: "docs"

copy:
- "static/*.*"
- "favicon.ico"
exclude:
- "_inc/**/*.*"
- "docs/**/*.*"
- "node_modules/**/*"
- "**/*~"

extras:
- slug: "/"
  source: "index.md"
  output: "index.html"

chapters:
- slug: "systems-programming"
  title: "Systems Programming"
  lede: "Using callbacks and promises to manipulate files and directories."
  keypoints:
  - FIXME
  exercises:
  - slug: significant-entries
    title: "Show only significant entries"

- slug: "unit-test"
  title: "Unit Testing"
  lede: "Testing software piece by piece."
  keypoints:
  - FIXME

- slug: "file-backup"
  title: "File Backup"
  lede: "Archiving files with directory structure."
  keypoints:
  - FIXME

- slug: "style-checker"
  title: "Style Checker"
  lede: "Checking that code conforms to style guidelines."
  keypoints:
  - FIXME
  exercises:
  - slug: function-length
    title: "How long are functions?"
  - slug: expression-depth
    title: "How deep are expressions?"
  - slug: downward-upward
    title: "Downward and upward"
  - slug: across-files
    title: "Aggregating across files"

- slug: "code-generator"
  title: "Code Generator"
  lede: "Modifying code to track coverage and execution times."
  keypoints:
  - FIXME

- slug: "page-templates"
  title: "Page Templates"
  lede: "Generating HTML pages from templates."
  keypoints:
  - FIXME

- slug: "module-loader"
  title: "Module Loader"
  lede: "Loading libraries on demand."
  keypoints:
  - FIXME

- slug: "module-bundler"
  title: "Module Bundler"
  lede: "Turning many files into one."
  keypoints:
  - FIXME

- slug: "layout-engine"
  title: "Layout Engine"
  lede: "Figuring out what goes where in a web page."
  keypoints:
  - FIXME

- slug: "text-editor"
  title: "Text Editor"
  lede: "A terminal text editor."
  keypoints:
  - FIXME

- slug: "doc-generator"
  title: "Documentation Generator"
  lede: "Generating documentation from comments embedded in code."
  keypoints:
  - FIXME

- slug: "http-server"
  title: "HTTP Server"
  lede: "Serving files and data."
  keypoints:
  - FIXME

- slug: "tabular-data"
  title: "Tabular Data"
  lede: "Storing data in tables."
  keypoints:
  - FIXME

- slug: "build-manager"
  title: "Build Manager"
  lede: "Re-running tasks that depends on other tasks."
  keypoints:
  - FIXME

- slug: "package-manager"
  title: "Package Manager"
  lede: "Getting and installing packages."
  keypoints:
  - FIXME

appendices:
- slug: "license"
  source: "LICENSE.md"

- slug: "conduct"
  source: "CONDUCT.md"

- slug: "bib"
  source: "bib.md"
  title: "Bibliography"

- slug: "links"
  source: "links.md"
  title: "Links"
