title: "Software Tools in JavaScript"
copyrightYear: 2020
repo: https://github.com/software-tools-in-javascript/stjs/
rootDir: "."
siteDir: "docs"

copy:
- ".nojekyll"
- "CNAME"
- "favicon.ico"
- "static/*.*"
exclude:
- "_inc/**/*.*"
- "docs/**/*.*"
- "node_modules/**/*"
- "**/*~"
sourceFiles:
- '*.html'
- '*.js'
- '*.json'
- '*.py'
- '*.sh'
- '*.txt'
- '*.yml'

extras:
- slug: "/"
  source: "index.md"
  output: "index.html"

chapters:
- slug: "systems-programming"
  title: "Systems Programming"
  lede: "Using callbacks to manipulate files and directories"
  exercises:
  - slug: "where-is-node"
    title: "Where is Node?"
  - slug: "trace-callback"
    title: "Tracing callbacks"
  - slug: "trace-anonymous"
    title: "Tracing anonymous callbacks"
  - slug: "significant-entries"
    title: "Significant entries"
  - slug: "glob-patterns"
    title: "Glob patterns"
  - slug: "array-filter"
    title: "Filtering arrays"
  - slug: "string-interpolation"
    title: "String interpolation"
  - slug: "destructuring-assignment"
    title: "Destructuring assignment"
  - slug: "counting-lines"
    title: "Counting lines"
  - slug: "rename-files"
    title: "Renaming files"

- slug: "promises"
  title: "Promises"
  lede: "Using promises to make callbacks easier"
  exercises:
  - slug: "explain-then"
    title: "Tracing promise execution"
  - slug: "multiple-catch"
    title: "Multiple catches"
  - slug: "catch-then"
    title: "Then after catch"
  - slug: "head-and-tail"
    title: "Head and tail"
  - slug: "line-histogram"
    title: "Histogram of line counts"
  - slug: "match-lines"
    title: "Select matching lines"
  - slug: "in-all"
    title: "Find lines in all files"
  - slug: "file-diff"
    title: "Find differences between two files"
  - slug: "trace-load"
    title: "Trace file loading"

- slug: "unit-test"
  title: "Unit Testing"
  lede: "Testing software piece by piece"
  exercises:
  - slug: "timing-tests"
    title: "Timing tests"
  - slug: "approx-equals"
    title: "Approximately equal"
  - slug: "rectangle-overlay"
    title: "Rectangle overlay"
  - slug: "selecting-tests"
    title: "Selecting tests"
  - slug: "tagging-tests"
    title: "Tagging tests"
  - slug: "mock-objects"
    title: "Mock objects"

- slug: "file-backup"
  title: "File Backup"
  lede: "Archiving files with directory structure"

- slug: "data-table"
  title: "Data Tables"
  lede: "Loading, saving, and manipulating tables efficiently"
  exercises:
  - slug: "loading-time"
    title: "Loading time"

- slug: "pattern-matching"
  title: "Pattern Matching"
  lede: "Using patterns to find things in data"
  exercises:
  - slug: "selectors-find-all"
    title: "Find all with query selectors"
  - slug: "selectors-attributes"
    title: "Select based on attributes"
  - slug: "regex-find-all"
    title: "Find all with regular expressions"
  - slug: "regex-one-or-more"
    title: "Find one or more with regular expressions"
  - slug: "regex-character-set"
    title: "Match sets of characters"
  - slug: "regex-any-efficiency"
    title: "Make repetition more efficient"

- slug: "regex-parser"
  title: "Parsing Expressions"
  lede: "Turning text into code"

- slug: "page-templates"
  title: "Page Templates"
  lede: "Generating HTML pages from templates"

- slug: "build-manager"
  title: "Build Manager"
  lede: "Updating files that depend on other files"

- slug: "layout-engine"
  title: "Layout Engine"
  lede: "Figuring out what goes where in a web page"

- slug: "text-editor"
  title: "Text Editor"
  lede: "A terminal text editor"

- slug: "file-interpolator"
  title: "File Interpolator"
  lede: "Manage source files that have been broken into pieces"

- slug: "module-loader"
  title: "Module Loader"
  lede: "Load source files as modules"

- slug: "module-bundler"
  title: "Module Bundler"
  lede: "Turning many files into one"

- slug: "package-manager"
  title: "Package Manager"
  lede: "Getting and installing packages"

- slug: "style-checker"
  title: "Style Checker"
  lede: "Checking that code conforms to style guidelines"
  exercises:
  - slug: "function-length"
    title: "Function length"
  - slug: "expression-depth"
    title: "Expression depth"
  - slug: "downward-and-upward"
    title: "Downward and upward"
  - slug: "across-files"
    title: "Aggregating across files"

- slug: "code-generator"
  title: "Code Generator"
  lede: "Modifying code to track coverage and execution times"

- slug: "doc-generator"
  title: "Documentation Generator"
  lede: "Generating documentation from comments embedded in code"

- slug: "virtual-machine"
  title: "Virtual Machine"
  lede: "Assembling and running low-level code"

- slug: "debugger"
  title: "Debugger"
  lede: "Running programs under the control of a breakpointing debugger"

- slug: "conclusion"
  title: "Conclusion"
  lede: "Where we have been and where you could go next"

appendices:
- slug: "bib"
  source: "bib.md"
  title: "Bibliography"
  latexSkipChapter: true

- slug: "license"
  source: "LICENSE.md"
  latexBefore: "\\appendix"

- slug: "conduct"
  source: "CONDUCT.md"

- slug: "contributing"
  source: "CONTRIBUTING.md"

- slug: "gloss"
  source: "gloss.md"
  title: "Glossary"

- slug: "links"
  source: "links.md"
  title: "Links"

# - slug: "solutions"
#   title: "Solutions"

- slug: "authors"
  source: "authors.md"
  title: "Authors"
