title: "Software Tools in JavaScript"
copyrightYear: 2020
repo: https://github.com/software-tools-in-javascript/stjs/
rootDir: "."
siteDir: "docs"

copy:
  - ".nojekyll"
  - "CNAME"
  - "favicon.ico"
  - "static/*.*"
  - "static/fonts/*/*.*"
exclude:
  - "_inc/**/*.*"
  - "docs/**/*.*"
  - "node_modules/**/*"
  - "**/*~"
sourceFiles:
  - '*.html'
  - '*.js'
  - '*.json'
  - '*.py'
  - '*.sh'
  - '*.txt'
  - '*.yml'

extras:
  - slug: "/"
    source: "index.md"
    output: "index.html"

chapters:
  - slug: "systems-programming"
    title: "Systems Programming"
    lede: "Using callbacks to manipulate files and directories"
    exercises:
      - slug: "x-where-is-node"
        title: "Where is Node?"
      - slug: "x-trace-callback"
        title: "Tracing callbacks"
      - slug: "x-trace-anonymous"
        title: "Tracing anonymous callbacks"
      - slug: "x-significant-entries"
        title: "Significant entries"
      - slug: "x-glob-patterns"
        title: "Glob patterns"
      - slug: "x-array-filter"
        title: "Filtering arrays"
      - slug: "x-string-interpolation"
        title: "String interpolation"
      - slug: "x-destructuring-assignment"
        title: "Destructuring assignment"
      - slug: "x-counting-lines"
        title: "Counting lines"
      - slug: "x-rename-files"
        title: "Renaming files"

  - slug: "promises"
    title: "Promises"
    lede: "Using promises to make callbacks easier"
    exercises:
      - slug: "x-explain-then"
        title: "Tracing promise execution"
      - slug: "x-multiple-catch"
        title: "Multiple catches"
      - slug: "x-catch-then"
        title: "Then after catch"
      - slug: "x-head-and-tail"
        title: "Head and tail"
      - slug: "x-line-histogram"
        title: "Histogram of line counts"
      - slug: "x-match-lines"
        title: "Select matching lines"
      - slug: "x-in-all"
        title: "Find lines in all files"
      - slug: "x-file-diff"
        title: "Find differences between two files"
      - slug: "x-trace-load"
        title: "Trace file loading"
      - slug: "x-any-all"
        title: "Any and all"

  - slug: "unit-test"
    title: "Unit Testing"
    lede: "Testing software piece by piece"
    exercises:
      - slug: "x-timing-tests"
        title: "Timing tests"
      - slug: "x-approx-equals"
        title: "Approximately equal"
      - slug: "x-rectangle-overlay"
        title: "Rectangle overlay"
      - slug: "x-selecting-tests"
        title: "Selecting tests"
      - slug: "x-tagging-tests"
        title: "Tagging tests"
      - slug: "x-mock-objects"
        title: "Mock objects"
      - slug: "x-setup-teardown"
        title: "Setup and teardown"
      - slug: "x-multi-test"
        title: "Multiple tests"
      - slug: "x-assert-set-map"
        title: "Assertions for sets and maps"
      - slug: "x-promises"
        title: "Testing promises"

  - slug: "file-backup"
    title: "File Backup"
    lede: "Archiving files with directory structure"
    exercises:
      - slug: "x-collision-odds"
        title: "Odds of collision"
      - slug: "x-io-streams"
        title: "Streaming I/O"
      - slug: "x-backup-sequence"
        title: "Sequencing backups"
      - slug: "x-json-manifests"
        title: "JSON manifests"
      - slug: "x-count-lines"
        title: "Testing line counting"
      - slug: "x-mock-hashes"
        title: "Mock hashes"
      - slug: "x-compare-manifests"
        title: "Comparing manifests"
      - slug: "x-from-to"
        title: "From one state to another"
      - slug: "x-file-history"
        title: "File history"
      - slug: "x-pre-commit"
        title: "Pre-commit hooks"

  - slug: "data-table"
    title: "Data Tables"
    lede: "Loading, saving, and manipulating tables efficiently"
    exercises:
      - slug: "x-row-fraction"
        title: "Varying filter behavior"
      - slug: "x-string-filter"
        title: "Filtering by strings"
      - slug: "x-join-performance"
        title: "Join performance"
      - slug: "x-join-optimization"
        title: "Join optimization"
      - slug: "x-flip-storage"
        title: "Flipping storage"
      - slug: "x-sparse-storage"
        title: "Sparse storage"
      - slug: "x-loading-time"
        title: "Loading time"
      - slug: "x-fixed-width"
        title: "Saving fixed-width strings"
      - slug: "x-variable-width"
        title: "Saving variable-width strings"
      - slug: "x-ascii-storage"
        title: "ASCII storage"

  - slug: "pattern-matching"
    title: "Pattern Matching"
    lede: "Using patterns to find things in data"
    exercises:
      - slug: "x-unit-tests"
        title: "Unit tests"
      - slug: "x-selectors-find-all"
        title: "Find all with query selectors"
      - slug: "x-selectors-attributes"
        title: "Select based on attributes"
      - slug: "x-child-selectors"
        title: "Child selectors"
      - slug: "x-regex-find-all"
        title: "Find all with regular expressions"
      - slug: "x-regex-one-or-more"
        title: "Find one or more with regular expressions"
      - slug: "x-regex-character-set"
        title: "Match sets of characters"
      - slug: "x-regex-any-efficiency"
        title: "Make repetition more efficient"
      - slug: "x-lazy-matching"
        title: "Lazy matching"
      - slug: "x-optional-matching"
        title: "Optional matching"

  - slug: "regex-parser"
    title: "Parsing Expressions"
    lede: "Turning text into code"
    exercises:
      - slug: "x-create-objects"
        title: "Create objects"
      - slug: "x-escape-characters"
        title: "Escape characters"
      - slug: "x-lazy-matching"
        title: "Lazy matching"
      - slug: "x-character-sets"
        title: "Character sets"
      - slug: "x-back-reference"
        title: "Back reference"
      - slug: "x-named-groups"
        title: "Named groups"
      - slug: "x-object-streams"
        title: "Object streams"
      - slug: "x-tokenize-html"
        title: "Tokenize HTML"
      - slug: "x-shunting-yard"
        title: "The Shunting Yard Algorithm"
      - slug: "x-error-handling"
        title: "Handling errors"

  - slug: "page-templates"
    title: "Page Templates"
    lede: "Generating HTML pages from templates"
    exercises:
      - slug: "x-tracing-execution"
        title: "Tracing execution"
      - slug: "x-unit-tests"
        title: "Unit tests"
      - slug: "x-trimming-text"
        title: "Trimming text"
      - slug: "x-literal-text"
        title: "Literal text"
      - slug: "x-include-files"
        title: "Including other files"
      - slug: "x-html-snippets"
        title: "HTML snippets"
      - slug: "x-yaml-headers"
        title: "YAML headers"
      - slug: "x-expand-all"
        title: "Expanding all files"
      - slug: "x-counting-loop"
        title: "Counting loops"
      - slug: "x-auxiliary-functions"
        title: "Auxiliary functions"

  - slug: "build-manager"
    title: "Build Manager"
    lede: "Updating files that depend on other files"
    exercises:
      - slug: "x-handle-failure"
        title: "Handle failure"
      - slug: "x-dry-run"
        title: "Dry run"
      - slug: "x-change-directories"
        title: "Change directories"
      - slug: "x-merge-files"
        title: "Merge files"
      - slug: "x-show-recipes"
        title: "Show recipes"
      - slug: "x-conditional-execution"
        title: "Conditional execution"
      - slug: "x-define-filesets"
        title: "Define filesets"
      - slug: "x-globbing"
        title: "Globbing"
      - slug: "x-use-hashes"
        title: "Use hashes"
      - slug: "x-auxiliary-functions"
        title: "Auxiliary functions"

  - slug: "layout-engine"
    title: "Layout Engine"
    lede: "Figuring out what goes where in a web page"

  - slug: "text-editor"
    title: "Text Editor"
    lede: "A terminal text editor"

  - slug: "file-interpolator"
    title: "File Interpolator"
    lede: "Manage source files that have been broken into pieces"

  - slug: "module-loader"
    title: "Module Loader"
    lede: "Load source files as modules"

  - slug: "module-bundler"
    title: "Module Bundler"
    lede: "Turning many files into one"

  - slug: "package-manager"
    title: "Package Manager"
    lede: "Getting and installing packages"

  - slug: "style-checker"
    title: "Style Checker"
    lede: "Checking that code conforms to style guidelines"
    exercises:
      - slug: "x-function-length"
        title: "Function length"
      - slug: "x-expression-depth"
        title: "Expression depth"
      - slug: "x-downward-and-upward"
        title: "Downward and upward"
      - slug: "x-across-files"
        title: "Aggregating across files"

  - slug: "code-generator"
    title: "Code Generator"
    lede: "Modifying code to track coverage and execution times"
  
  - slug: "doc-generator"
    title: "Documentation Generator"
    lede: "Generating documentation from comments embedded in code"

  - slug: "virtual-machine"
    title: "Virtual Machine"
    lede: "Assembling and running low-level code"

  - slug: "debugger"
    title: "Debugger"
    lede: "Running programs under the control of a breakpointing debugger"

  - slug: "code-analyzer"
    title: "Code Analyzer"
    lede: "Analyzing source code"

  - slug: "conclusion"
    title: "Conclusion"
    lede: "Where we have been and where you could go next"

appendices:
  - slug: "bib"
    source: "bib.md"
    title: "Bibliography"
    latexSkipChapter: true

  - slug: "license"
    source: "LICENSE.md"
    latexBefore: "\\appendix"

  - slug: "conduct"
    source: "CONDUCT.md"

  - slug: "contributing"
    source: "CONTRIBUTING.md"
  
  - slug: "gloss"
    source: "gloss.md"
    title: "Glossary"

  - slug: "links"
    source: "links.md"
    title: "Links"

  # - slug: "solutions"
  #   title: "Solutions"

  - slug: "authors"
    source: "authors.md"
    title: "Authors"
