# General.
title: "Software Tools in JavaScript"
subtitle: "An incremental introduction to software design"
author: "Greg Wilson"
year: "2020"
version: "0.3"
email: "gvwilson@third-bit.com"
domain: "https://stjs.tech"
repo: "https://github.com/software-tools-in-javascript/stjs/"

# Jekyll settings.
repository: <USERNAME>/<PROJECT>
defaults:
- scope:
    path: ""
  values:
    layout: "page"
kramdown:
  toc_levels: "2"
exclude:
- "Makefile"
- "Nemilov.cls"
- "README.md"
- "bin"
- "etc"
- "*.Rmd"
- "*.aux"
- "*.bbl"
- "*.bcf"
- "*.blg"
- "*.csv"
- "*.idx"
- "*.ilg"
- "*.ind"
- "*.ipynb"
- "*.log"
- "*.out"
- "*.pdf"
- "*.pyg"
- "*.tex"
- "*.toc"
- "*.xlsx"
- "*/*.py"
- "*/*/MANIFEST.md"
- "*/MANIFEST.md"
- "*/Makefile"
- "*/bin/*"
- "*/data/*"
- "*/log/*"
- "*/test/*"
- "_minted-book"
- "package.json"
- "unused"
