# Bajel build commands.

help: # Show available commands.
  exec: "fgrep -e ': #' build.yaml | fgrep -v -e build.yaml | column -t -s ':'"

serve: # Run a server on port 4000.
  exec: "http-server docs -p 4000"
  deps:
  - docs/index.html

check: # Check that everything is consistent.
  exec: "bin/check.js --input docs/index.html docs/*/index.html"

clean: # Tidy up workspace.
  exec: "bin/clean.js book.aux book.log book.out book.pdf book.tex book.toc '**/*~'"

bib.md: # Rebuild bibliography.
  exec: "bin/bib.js --input bib.yml --output bib.md"
  deps:
  - bin/bib.js
  - bib.yml

docs/index.html: # Rebuild HTML version.
  exec: "bin/html.js --rootDir . --outputDir docs --configFile config.yml --linksFile links.yml"
  deps:
  - source
  - bin/html.js
  - bib.md
  - gloss.md
  - inc/foot.html
  - inc/head.html
  - static/site.css
  - static/site.js

gloss.md: # Rebuild glossary file.
  exec: "bin/gloss.js --glosario --input gloss.yml --output gloss.md --sources index.md */*.md"
  deps:
  - source
  - bin/gloss.js
  - gloss.yml

book.tex: # Create LaTeX version of material.
  exec: "bin/latex.js --config config.yml --htmlDir docs --outputFile book.tex --head tex/head.tex --foot tex/foot.tex --numbering docs/numbering.js"
  deps:
  - bin/latex.js
  - docs/index.html
  - tex/foot.tex
  - tex/head.tex
  - tex/krantz.cls

book.pdf: # Create printable version of material.
  exec: "pdflatex book && pdflatex book"
  deps:
  - book.tex

catalog: # Create catalog of nodes, attributes, and values.
  exec: "bin/catalog.js --ignore --input docs/index.html docs/*/index.html"
  deps:
  - docs/index.html

wordlist: # Create a list of words found in HTML files.
  exec: "bin/wordlist.js --input docs/index.html docs/*/index.html | aspell list | sort | uniq | diff -B - tex/wordlist.txt"
  deps:
  - docs/index.html

# Fake target for dependencies (Bajel doesn't support wildcard expansion).
source:
  deps:
  - index.md
  - CONDUCT.md
  - CONTRIBUTING.md
  - LICENSE.md
  - authors.md
  - links.md
  - build-manager/index.md
  - code-generator/index.md
  - conclusion/index.md
  - doc-generator/index.md
  - file-backup/index.md
  - http-server/index.md
  - layout-engine/index.md
  - module-bundler/index.md
  - module-loader/index.md
  - package-manager/index.md
  - page-templates/index.md
  - style-checker/index.md
  - systems-programming/index.md
  - tabular-data/index.md
  - text-editor/index.md
  - unit-test/index.md
