copyrightYear: 2020
url: https://stjs.tech
repo: https://github.com/software-tools-in-javascript/stjs/
rootDir: "."
defaultImage: "/static/tools-small.jpg"
email: "info@stjs.tech"
title: "Software Tools in JavaScript"

sourceFiles:
  - '*.as'
  - '*.html'
  - '*.js'
  - '*.json'
  - '*.mx'
  - '*.py'
  - '*.sh'
  - '*.txt'
  - '*.yml'
  - 'figures/*.svg'
