build:
  deps:
  - copy-file-unfiltered.text
  - glob-all-files.text
  - glob-get-then-filter-pedantic.text
  - list-dir-function-defined.text
  - list-dir-wrong.text

copy-file-unfiltered.text:
  deps:
  - copy-file-unfiltered.js
  - copy-file-unfiltered.sh
  exec: "bash copy-file-unfiltered.sh > copy-file-unfiltered.text"

glob-all-files.text:
  deps:
  - glob-all-files.js
  exec: "node glob-all-files.js > glob-all-files.text"

glob-get-then-filter-pedantic.text:
  deps:
  - glob-get-then-filter-pedantic.js
  exec: "node glob-get-then-filter-pedantic.js > glob-get-then-filter-pedantic.text"

list-dir-function-defined.text:
  deps:
  - list-dir-function-defined.js
  - list-dir-function-defined.sh
  exec: "bash list-dir-function-defined.sh > list-dir-function-defined.text"

list-dir-wrong.text:
  deps:
  - list-dir-wrong.js
  - list-dir-wrong.sh
  exec: "(bash list-dir-wrong.sh >& list-dir-wrong.text) || true"
