build:
  deps:
  - dry-run.text
  - pray.text

dry-run.text:
  deps:
  - dry-run.js
  exec: "node dry-run.js > dry-run.text"

pray.text:
  deps:
  - pray.js
  - pray.sh
  exec: "bash pray.sh > pray.text"
