build:
  deps:
  - hash-file.text
  - hash-stream.text
  - hash-text.text
  - run-hash-existing-async.text
  - run-hash-existing-promise.text
  - test-backup.text
  - test-check-filesystem.text
  - tree-test.text

hash-file.text:
  deps:
  - hash-file.js
  - hash-file.sh
  exec: "bash hash-file.sh > hash-file.text"

hash-stream.text:
  deps:
  - hash-stream.js
  - hash-stream.sh
  exec: "bash hash-stream.sh > hash-stream.text"

hash-text.text:
  deps:
  - hash-text.js
  - hash-text.sh
  exec: "bash hash-text.sh > hash-text.text"

run-hash-existing-promise.text:
  deps:
  - run-hash-existing-promise.js
  - run-hash-existing-promise.sh
  exec: "bash run-hash-existing-promise.sh > run-hash-existing-promise.text"

run-hash-existing-async.text:
  deps:
  - run-hash-existing-async.js
  - run-hash-existing-async.sh
  exec: "bash run-hash-existing-async.sh > run-hash-existing-async.text"

test-backup.text:
  deps:
  - test-backup.sh
  exec: "bash test-backup.sh > test-backup.text"

test-check-filesystem.text:
  deps:
  - test-check-filesystem.sh
  exec: "bash test-check-filesystem.sh > test-check-filesystem.text"

tree-test.text:
  deps:
  - tree-test.sh
  exec: "bash tree-test.sh > tree-test.text"
