build:
  deps:
  - callbacks-with-timeouts.text
  - callbacks-with-zero-timeouts.text
  - count-lines-globbed-files.text
  - count-lines-histogram.text
  - count-lines-single-file.text
  - count-lines-with-stat.text
  - non-blocking.text
  - not-callbacks-alone.text
  - promise-example.text
  - set-immediate.text
  - use-pledge-chained.text
  - use-pledge-motivation.text
  - use-pledge-reject.text
  - use-pledge-return.text
  - use-promise-chained.text

callbacks-with-timeouts.text:
  deps:
  - callbacks-with-timeouts.js
  exec: "node callbacks-with-timeouts.js > callbacks-with-timeouts.text"

callbacks-with-zero-timeouts.text:
  deps:
  - callbacks-with-zero-timeouts.js
  exec: "node callbacks-with-zero-timeouts.js > callbacks-with-zero-timeouts.text"

count-lines-globbed-files.text:
  deps:
  - count-lines-globbed-files.sh
  - count-lines-globbed-files.js
  exec: "bash count-lines-globbed-files.sh > count-lines-globbed-files.text"

count-lines-histogram.text:
  deps:
  - count-lines-histogram.sh
  - count-lines-histogram.js
  exec: "bash count-lines-histogram.sh > count-lines-histogram.text"

count-lines-single-file.text:
  deps:
  - count-lines-single-file.sh
  - count-lines-single-file.js
  exec: "bash count-lines-single-file.sh > count-lines-single-file.text"

count-lines-with-stat.text:
  deps:
  - count-lines-with-stat.sh
  - count-lines-with-stat.js
  exec: "bash count-lines-with-stat.sh > count-lines-with-stat.text"

non-blocking.text:
  deps:
  - non-blocking.js
  exec: "node non-blocking.js > non-blocking.text"

not-callbacks-alone.text:
  deps:
  - not-callbacks-alone.js
  exec: "node not-callbacks-alone.js > not-callbacks-alone.text"

promise-example.text:
  deps:
  - promise-example.js
  exec: "node promise-example.js > promise-example.text"

set-immediate.text:
  deps:
  - set-immediate.js
  exec: "node set-immediate.js > set-immediate.text"

use-pledge-chained.text:
  deps:
  - use-pledge-chained.js
  exec: "node use-pledge-chained.js > use-pledge-chained.text"

use-pledge-motivation.text:
  deps:
  - use-pledge-motivation.js
  exec: "node use-pledge-motivation.js > use-pledge-motivation.text"

use-pledge-reject.text:
  deps:
  - use-pledge-reject.js
  exec: "node use-pledge-reject.js > use-pledge-reject.text"

use-pledge-return.text:
  deps:
  - use-pledge-return.js
  exec: "node use-pledge-return.js > use-pledge-return.text"

use-promise-chained.text:
  deps:
  - use-promise-chained.js
  exec: "node use-promise-chained.js > use-promise-chained.text"
